spring:
  datasource:
    url: jdbc:h2:mem:transfer-schedule
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2