spring:
  datasource:
    url: jdbc:h2:mem:transfer-schedule
    driverClassName: org.h2.Driver
    username: sa
    password: 123123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2